# -*- coding: utf-8 -*-
"""bigdata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ChcqFn-oMZ_9VnvpnyuCMQYZZXsQ6QKu

1-1
"""

import pandas as pd
import numpy as np

s = pd.read_csv('/content/edu_bigdata_imp1.csv', encoding='Big5', low_memory=False)

sFiltered = s[s['PseudoID'] == 39]

sFiltered = sFiltered.dropna(subset=['dp001_review_sn'])

uniqueValue = sFiltered['dp001_review_sn'].unique()

print(len(uniqueValue))

"""1-2"""

import pandas as pd
import numpy as np

s = pd.read_csv('/content/edu_bigdata_imp1.csv', encoding='Big5', low_memory=False)

sFiltered = s[s['PseudoID'] == 39]

sFiltered = sFiltered.dropna(subset=['dp001_question_sn'])

uniqueValue = sFiltered['dp001_question_sn'].unique()

print(len(uniqueValue))

"""2-1"""

import pandas as pd
import numpy as np